pr: none

pool:
    vmImage: 'windows-latest'

steps:
    - task: NuGetCommand@2
      displayName: NuGet restore
      inputs:
        solution: src\ServiceControl.sln
        configurationToPack: Release
        nugetConfigPath: nuget.config
        feedsToUse: config
    - task: VSBuild@1
      displayName: Build solution Operations.sln
      inputs:
        solution: src\ServiceControl.sln
        vsVersion: 16.0
        platform: any cpu
        configuration: Release
        maximumCpuCount: true
        msbuildArchitecture: x64
    - task: Docker@2
      inputs:
        containerRegistry: 'daad1d05-17d9-4c80-91af-18c121916054'
        repository: 'particular/servicecontrol.azureservicebus-windows'
        command: 'buildAndPush'
        Dockerfile: 'servicecontrol.azureservicebus-windows.dockerfile'
        tags: 'latest'